name: BestSure Monitor

on:
  schedule:
    - cron: '*/30 * * * *' # 30분마다 자동 실행
  workflow_dispatch:      # 사용자가 수동으로 실행해볼 수 있는 버튼 생성

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install requests beautifulsoup4

      - name: Run Script
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
        run: python bot.py

      - name: Commit changes
        run: |
          git config --global user.name 'github-actions'
          git config --global user.email 'actions@github.com'
          git add last_content.txt
          git commit -m "Update last content" || echo "No changes to commit"
          git push
